language: ruby

rvm:
  - 2.6.3

services:
  - postgresql
  - redis-server

addons:
  postgresql: '9.6'

env:
  - TEST_DATABASE_USERNAME=postgres

cache: bundler

before_install:
 - gem update --system
 - gem install bundler --no-document

before_script:
#   - psql -c "CREATE USER mutuba WITH PASSWORD 'mutuba';" -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
