version: '3'
services:
  db:
    image: postgres

    volumes: &volumes
      - ./postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    environment: &environment
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: "trust"

  web:
    build: .

    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    volumes:
      - .:/myapp

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - db

volumes:
  pgdata: