
# default: &default
#   adapter: postgresql
#   host: localhost
#   port: 5432
#   encoding: utf8
#   pool: 5
#   database: rails-json-api
# username: <%= ENV['DATABASE_USER'] %>
# password: <%= ENV['DATABASE_PASSWORD'] %>

# development: &default
#   adapter: postgresql
#   host: localhost
#   port: 5432
#   encoding: utf8
#   pool: 5
#   database: rails-json-api-dev
# username: <%= ENV['DATABASE_USER'] %>
# password: <%= ENV['DATABASE_PASSWORD'] %>


# test: &default
#   adapter: postgresql
#   host: localhost
#   port: 5432
#   encoding: utf8
#   pool: 5
#   database: rails-json-api-test
# username: <%= ENV['DATABASE_USER'] %>
# password: <%= ENV['DATABASE_PASSWORD'] %>

# production: &default
#   adapter: postgresql
#   host: localhost
#   port: 5432
#   encoding: utf8
#   pool: 5
#   database: rails-json-api-prod
# username: <%= ENV['DATABASE_USER'] %>
# password: <%= ENV['DATABASE_PASSWORD'] %>


development:
  adapter: postgresql
  host: db
  database: todo_docker
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  adapter: postgresql
  host: db
  database: todo_docker_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>