
default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: utf8
  pool: 5
  database: rails-json-api
  username: mutuba
  password: baraka11

development: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: utf8
  pool: 5
  database: rails-json-api-dev
  username: mutuba
  password: baraka11


test: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: utf8
  pool: 5
  database: rails-json-api-test
  username: mutuba
  password: baraka11

production: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: utf8
  pool: 5
  database: rails-json-api-prod
  username: mutuba
  password: baraka11






# development:
#   adapter: postgresql
#   host: db
#   database: todo_docker
#   username: mutuba
#   password: baraka11

# test:
#   adapter: postgresql
#   host: db
#   database: todo_docker_test
#   username: mutuba
#   password: baraka11