
default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: utf8
  pool: 5
  database: rails-json-api
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: rails-json-api-dev

test:
  <<: *default
  database: rails-json-api-test


production:
  <<: *default
  database: rails-json-api-prod


  
# docker settings

# development:
#   adapter: postgresql
#   host: db
#   database: todo_docker
#   username: <%= ENV['POSTGRES_USER'] %>
#   password: <%= ENV['POSTGRES_PASSWORD'] %>

# test:
#   adapter: postgresql
#   host: db
#   database: todo_docker_test
#   username: <%= ENV['POSTGRES_USER'] %>
#   password: <%= ENV['POSTGRES_PASSWORD'] %>

#   has_many :reviews, inverse_of: :author, foreign_key: 'author_id'

# class Review < ApplicationRecord
#   belongs_to :author, class_name: 'User'
# end
